-- Initial script to create the database and the table
BEGIN;

-- Create the database
DROP TABLE IF EXISTS "users" CASCADE;

-- Create the table
CREATE TABLE "users" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) DEFAULT NULL,
    "accent_color" VARCHAR(255) DEFAULT NULL,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Commit the transaction
COMMIT;